---
- hosts: all
  sudo: yes
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
    - name: "Install {{ item }}"
      apt: pkg="{{ item }}" state=present
      with_items:
        - htop
        - curl
        - unzip
    - name: Install php5-dev
      apt: pkg=php5-dev state=latest
      when: ansible_distribution == "Debian"
