- name: Install php
  apt: pkg="{{ item }}" state=latest
  with_items:
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-mysql
- name: Start php-fpm service
  service: name=php5-fpm state=started enabled=true
