---
- name: Install MySQL, WordPress, Nginx and PHP-FPM
  hosts: all
  sudo: yes

  roles:
    - { role: common, tags: common }
    - { role: mysql, tags: mysql }
    - { role: php5, tags: php }
    - { role: nginx, tags: nginx }
    - { role: wordpress, tags: wordpress }
